quarkus.quinoa.package-manager=pnpm
quarkus.quinoa.package-manager-install.pnpm-version=10.32.1
quarkus.quinoa.package-manager-install.node-version=24.14.0
quarkus.quinoa.package-manager-install=true
quarkus.quinoa.force-install=true
quarkus.quinoa.ui-root-path=/
quarkus.quinoa.dev-server.port=50999

